version: 2
models:
  - name: fct_active_days
    description: Counts the number of days a user viewed at least 10 minutes of content
    columns: 
      - name: account_id
        description: '{{ doc("account_id") }}'
        tests:
          - not_null
      - name: context_campaign_source
        description: Channel source of paid campaign
      - name: context_campaign_name
        description: Name assigned to a paid campaign
      - name: context_campaign_term
        description: Name of term used to identify a campaign strategy.
      - name: signed_up_at
        description: Date a user signed up for Philo.
      - name: first_paid_at
        description: Date a user first paid for Philo.
      - name: ltv_revenue
        description: Total revenue (subscriptions and ads) per user account.
      - name: active_days
        desciption: The number of days where an account user watched more than 10 minutes.
      - name: last_show_watched
        desscription: The show title of the last show a user watched.
      - name: last_playback_time 
        description: Date a show or movies was last watched.
  - name: fct_time_to_stream_start
    description: Counts the number of seconds between an app being launched and the first stream start
    columns: 
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: platform
        description: Platform on which this stream was played
      - name: open_date
        description: the date on which the app was opened
      - name: open_time
        description: time when the app was opened
      - name: time_to_stream_start
        description: seconds from app launch to first stream start