version: 2

sources:
  - name: facebook_ads
    database: warehouse
    schema: facebook_ads
    loader: segment
    loaded_at_field: uuid_ts

    quoting:
      database: true
      schema: true
      identifier: false
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 72, period: hour}

    tables:
      - name: ads
        freshness: null # do not check, slowly changing table
      - name: ad_sets
        freshness: null # do not check, slowly changing table
      - name: ad_accounts
      - name: campaigns
        freshness: null # do not check, slowly changing table
      - name: insights