version: 2

models:
  - name: rails_sync_users_with_content_access_stage
    description: Nightly sync that indicates which users/accounts have content access
    columns:
      - name: account_id
        description: '{{ doc("account_id") }}'
      - name: biller
        description: Which of our billers the account is actively subscribed through
      - name: status
        description: Status field indicating if the account in trial, in extended trial, or post-trial
      - name: product_sku
        description: The activated product SKU
      - name: activated_plan
        description: The content plan the account has access to, potentially 'null'
      - name: reported_at
        description: When the sync process ran on the rails db