version: 2

models:
  - name: dataserver_prod_channel_favorite_source
    description: dataserver channel_favorite_source events
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: channel_id
        description: The channel the user is favoriting
      - name: timestamp
        description: the timestamp of the event
  - name: dataserver_prod_channel_unfavorite_source
    description: dataserver channel_unfavorite_source events
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: channel_id
        description: The channel the user is unfavoriting
      - name: timestamp
        description: the timestamp of the event
  - name: dataserver_prod_experiment_viewed_source
    description: user viewed an experiment
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: experiment_name
        description: The name of the experiment
      - name: experiment_id
        description: The id of the experiment
      - name: variant_name
        description: The variant of the experiment to which the user belongs
      - name: variant_id
        description: The variant id
      - name: start_date
        description: The start date of the experiment
      - name: event_timestamp
        description: the timestamp of the event
  - name: dataserver_prod_message_sent_to_client_source
    description: notification events for sent messages when a message is requested by the client app
    columns:
      - name: account_id
        description: '{{ doc("account_id") }}'
      - name: message_id
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
        tests:
          - not_null:
              severity: error
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
        tests:
          - not_null:
              severity: error
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: message_external_id
        description: internally set message id (set on the backend and sent to segment)
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: message_event
        description: The type of message that was recorded
        tests:
          - accepted_values:
              values: [
                'message_received'
                , 'message_clicked'
                , 'message_opened'
                , 'message_dismissed'
                , 'message_sent'
                , 'message_sent_to_client'
              ]  
  - name: dataserver_prod_playback_session_created_source
    description: dataserver playback_session_created events
    columns:
      - name: as_number
        description: '{{ doc("as_number") }}'
      - name: as_name
        description: '{{ doc("as_name") }}'
      - name: geohash
        description: '{{ doc("geohash") }}'
      - name: dma
        description: '{{ doc("dma") }}'
      - name: loaded_at
        description: When the recorded was added to the data warehouse
      - name: sutured_pid
        description: '{{ doc("sutured_pid") }}'
      - name: is_new_session
        description: '{{ doc("is_new_session") }}'
      - name: manifest_environment
        description: '{{ doc("manifest_environment") }}'
      - name: content_cdn_host
        description: '{{ doc("content_cdn_host") }}'
      - name: is_sender
        description: '{{ doc("is_sender") }}'
      - name: played_asset_id
        description: '{{ doc("played_asset_id") }}'
      - name: tile_group_id
        description: '{{ doc("tile_group_id") }}'
      - name: synthetic_channel_id
        description: synthetic channel id
  - name: dataserver_prod_scrolled_source
    description: dataserver scrolled events across tiles and streams
    columns:
      - name: environment_analytics_version
        description: Analytics version
      - name: event_text 
        description: describes event sent 
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
      - name: initial_index
        description: index from which the skip occured 
      - name: original_timestamp
        description: When the event occurred according to dataserver down to the millisecond
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: scroll_distance 
        description: depth of scroll, equal to the difference between terminal and initial index 
      - name: terminal_index 
        description: index on which the skip ended
      - name: tile_group_id
        description: '{{ doc("tile_group_id") }}'
      - name: tile_group_id
        description: Title of the tile group 
      - name: uuid_ts
        description: Segment's universally unique identifier and the epoch timestamp when the event was created, in milliseconds - events must be sent as soon as possible, as events created more than 3 hours before the current time are rejected.
      - name: user_id
        description: '{{ doc("user_id") }}' 
      - name: uuid
        description: Segment's universally unique identifier is a 128-bit label for data events
  - name: dataserver_prod_show_save_source
    description: dataserver prod show save events
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: show_id
        description: The global identifier for the show.
      - name: sent_at
        description: The time the client indicates the save occurred.
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: timestamp
        description: '{{ doc("timestamp") }}'
  - name: dataserver_prod_show_unsave_source
    description: dataserver prod show unsave events
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: show_id
        description: The global identifier for the show.
      - name: sent_at
        description: The time the client indicates the unsave occurred.
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: timestamp
        description: '{{ doc("timestamp") }}'
  - name: dataserver_prod_search_term_source
    description: dataserver prod search terms
    columns:
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: term
        description: The search query.
      - name: user_agent
        description: The user agent of the client issuing the request.
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: timestamp
        description: '{{ doc("timestamp") }}'
  - name: dataserver_prod_errors_source
    description: dataserver prod error events (currently, only startup errors as these errors take place before stream start)
    columns:
      - name: event_text
        description: describes event sent 
      - name: error_type
        description: describes which dataserver error event is sending (createPlaybackSession vs checkPlaybackSession)
      - name: original_timestamp
        description: When the event occurred according to dataserver down to the millisecond
      - name: received_at
        description: when the error event was received
      - name: playback_session_id
        description: '{{ doc("playback_session_id") }}'
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: error_code
        description: specific dataserver error code in format ds-x.x.x
      - name: error_description
        description: dataserver error code description such as PLAYER_NOT_FOUND
      - name: requested_asset_id
        description: id of requested asset 
      - name: platform
        description: client platform
      - name: device_type
        description: device_type
      - name: context_user_agent
        description: the browser user agent string
      - name: loaded_at
        description: '{{ doc("uuid_ts") }}'
      - name: player_id
        description: unique id for device and account profile
      - name: environment_analytics_version
        description: analytics version