version: 2

sources:
  - name: web_prod
    database: warehouse
    schema: web_prod
    loader: segment
    loaded_at_field: uuid_ts

    quoting:
      database: true
      schema: true
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: experiment_viewed
        freshness: null # do not check freshness for this table
      - name: identifies
      - name: interact
      - name: message_clicked
      - name: message_dismissed
      - name: message_opened
      - name: message_received
      - name: pages
      - name: player_state_changed
      - name: poll_submit
      - name: stream_start
      - name: stream_end
      - name: stream_error
      - name: rebuffering_start
      - name: rebuffering_end 
