version: 2

sources:
  - name: ios_prod
    database: warehouse
    schema: ios_prod
    loader: segment
    loaded_at_field: uuid_ts

    quoting:
      database: true
      schema: true
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: application_installed
      - name: application_opened
      - name: dialog_approved
      - name: dialog_dismissed
      - name: dialog_displayed
      - name: identifies
      - name: interact
      - name: message_clicked
      - name: message_dismissed
      - name: message_opened
      - name: message_received
      - name: player_state_changed
      - name: poll_submit
      - name: screens
      - name: signup_auth_success
      - name: stream_start
      - name: stream_end
      - name: stream_error
      - name: rebuffering_start
      - name: rebuffering_end
      - name: payment_provider_purchase_error
      - name: payment_provider_purchase_start
      - name: payment_provider_purchase_success
