version: 2

sources:
  - name: appsflyer
    database: warehouse
    schema: appsflyer
    loader: rails_ott_analytics_scripts
    loaded_at_field: event_time

    quoting:
      database: true
      schema: true
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 36, period: hour}

    tables:
      - name: amazon_installs
      - name: google_installs
      - name: ios_installs
