version: 2

models:
  - name: tvos_prod_application_opened_source
    description: Launch events tracked via segment on tvos prod
    columns:
      - name: anonymous_id
        tests:
          - not_null
      - name: visited_at
        tests:
          - not_null
  - name: tvos_prod_identifies_source
    description: Identify events that connect an anonymous id to a Philo user_id
    columns:
      - name: anonymous_id
        description: Segment generated anonymous id
        tests: 
          - not_null
      - name: user_id
        description: '{{ doc("user_id") }}'
        tests: 
          - not_null
      - name: received_at
        description: When the identify event was received
      - name: context_device_id
        description: The tvos device identifier
      - name: timestamp
        description: When the identify event occurred according to tvos
  - name: tvos_prod_player_state_changed_source
    description: Video playback events that tracked what users watched via segment on tvos prod
  - name: tvos_prod_poll_submit_source
    description: Answers to our how did you hear about us survey
    columns:
      - name: event_id
        description: '{{ doc("event_id") }}'
      - name: user_id
        description: '{{ doc("user_id") }}'
        tests:
          - not_null
      - name: poll_name
        description: The name of the Philo poll answered
      - name: question
        description: The question that was displayed to the user
      - name: answer
        description: The poll answer selected
      - name: environment_analytics_version
        description: Analytics version which indicates what possible answers were available in the poll
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
  - name: tvos_prod_screens_source
    description: Event fired when a screen loads in the tvos app
    columns: 
      - name: anonymous_id
        description: '{{ doc("anonymous_id") }}'
        tests:
          - not_null
      - name: context_device_id
        description: A unique identifier for the device the screen was requested from 
      - name: environment_analytics_version
        description: '{{ doc("environment_analytics_version") }}'
      - name: event_id
        description: '{{ doc("event_id") }}'
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: screen_name
        description: A name, typically descriptive, for the screen loaded
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: visited_at 
        description: The timestamp the event was received by Segment's tracking service.
  - name: tvos_prod_signup_auth_submit_source
    description: The last event recorded prior to identify in the signup flow
  - name: tvos_prod_message_clicked_source 
    description: clicked message notification events from tvos
    columns:
      - name: message_id
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
        tests:
          - not_null:
              severity: error
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
        tests:
          - not_null:
              severity: error
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: message_external_id
        description: internally set message id (set on the backend and sent to segment)
      - name: message_channel
        description: channel the notification is delivered through
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: message_event
        description: The type of message that was recorded
        tests:
          - accepted_values:
              values: [
                'message_clicked'
              ]
  - name: tvos_prod_message_dismissed_source 
    description: dismissed message notification events from tvos
    columns:
      - name: message_id
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
        tests:
          - not_null:
              severity: error
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
        tests:
          - not_null:
              severity: error
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: message_external_id
        description: internally set message id (set on the backend and sent to segment)
      - name: message_channel
        description: channel the notification is delivered through
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: message_event
        description: The type of message that was recorded
        tests:
          - accepted_values:
              values: [
                'message_dismissed'
              ]
  - name: tvos_prod_message_opened_source 
    description: opened message notification events from tvos
    columns:
      - name: message_id
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
        tests:
          - not_null:
              severity: error
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
        tests:
          - not_null:
              severity: error
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: message_external_id
        description: internally set message id (set on the backend and sent to segment)
      - name: message_channel
        description: channel the notification is delivered through
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: message_event
        description: The type of message that was recorded
        tests:
          - accepted_values:
              values: [
                'message_opened'
              ]
  - name: tvos_prod_message_received_source 
    description: received message notification events from tvos
    columns:
      - name: message_id
      - name: loaded_at
        description: '{{ doc("loaded_at") }}'
        tests:
          - not_null:
              severity: error
      - name: event_timestamp
        description: '{{ doc("event_timestamp") }}'
        tests:
          - not_null:
              severity: error
      - name: user_id
        description: '{{ doc("user_id") }}'
      - name: message_external_id
        description: internally set message id (set on the backend and sent to segment)
      - name: message_channel
        description: channel the notification is delivered through
      - name: received_at
        description: '{{ doc("received_at") }}'
      - name: message_event
        description: The type of message that was recorded
        tests:
          - accepted_values:
              values: [
                'message_received'
              ]