version: 2

sources:
  - name: google_ads
    database: warehouse
    schema: google_ads
    loader: segment
    loaded_at_field: uuid_ts

    quoting:
      database: true
      schema: true
      identifier: false
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 72, period: hour} 
    tables:
      - name: ads
        freshness: null # do not check, slowly changing table
      - name: ad_groups
        freshness: null # do not check, slowly changing table
      - name: ad_performance_reports
      - name: click_performance_reports
      - name: campaigns
        freshness: null # do not check, slowly changing table
      - name: campaign_performance_reports
    
  
    

